server:
  port: 64415

spring:
  application:
    name: channel-service

eureka:
  instance:
    instance-id: channel-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka